{
 "title": "Build Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "build_id",
    "label": "Build ID",
    "query": {
     "query": "label_values(kube_pod_info, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Volume usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(docker_volume_kb_total{dind_pod_name=\"dind-$build_id\"} - docker_volume_kb_available{dind_pod_name=\"dind-$build_id\"})/1024^2",
     "legendFormat": "Volume usage (GB)"
    },
    {
     "expr": "docker_volume_kb_total{dind_pod_name=\"dind-$build_id\"}/1024^2",
     "legendFormat": "Volume Size"
    }
   ]
  },
  {
   "title": "Dind Container CPU usage",
   "type": "graph",
   "description": "Shows CPU usage in CPU units",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=\"dind-$build_id\",container=\"dind\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=\"dind-$build_id\", resource=\"cpu\"}\r\n)\r\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=\"dind-$build_id\", resource=\"cpu\"}\r\n)\r\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Dind Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=\"dind-$build_id\", container=\"dind\", image!=\"\"}) by (container)",
     "legendFormat": "{{conrtainer}}"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\",pod=\"dind-$build_id\", resource=\"memory\"}\r\n)\r\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=\"dind-$build_id\", resource=\"memory\"}\r\n)\r\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Dind Container Network Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"dind-$build_id\"}[100s])) * 8 / 1000000",
     "legendFormat": "Network Receive Mbit/s"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"dind-$build_id\"}[100s])) * 8 / 1000000",
     "legendFormat": "Network Transmit Mbit/s"
    }
   ]
  }
 ]
}