{
 "title": "Pipeline metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pipeline_id",
    "label": "Pipeline ID",
    "query": {
     "query": "label_values(kube_pod_labels, label_io_codefresh_pipeline_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Consumption(AVG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg without (pod) (\n  avg by (pod) (\n    rate(container_cpu_usage_seconds_total{pod=~\"^dind-.*\",container!=\"POD\"}[40s])\n  )\n  * on(pod) group_left(label_io_codefresh_pipeline_id) \n  kube_pod_labels{label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\"}\n)"
    }
   ]
  },
  {
   "title": "Memory Consumption(AVG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (label_io_codefresh_pipeline_id) (\n  avg by (pod, label_io_codefresh_pipeline_id) (\n    container_memory_usage_bytes{pod=~\"^dind-[0-9].*\", container_name!=\"POD\"}\n    * on(pod) group_left(label_io_codefresh_pipeline_id) \n    kube_pod_labels{label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Volume Consumption(AVG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (io_codefresh_pipeline_id) (\n\t(docker_volume_kb_total{io_codefresh_pipelineId=\"$pipeline_id\"} - docker_volume_kb_available{io_codefresh_pipelineId=\"$pipeline_id\"})\n)"
    }
   ]
  },
  {
   "title": "CPU Consumption(MAX)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max without (pod) (\n  avg by (pod) (\n    rate(container_cpu_usage_seconds_total{pod=~\"^dind-.*\",container!=\"POD\"}[40s])\n  )\n  * on(pod) group_left(label_io_codefresh_pipeline_id) \n  kube_pod_labels{label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\"}\n)"
    }
   ]
  },
  {
   "title": "Memory Consumption(MAX)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (label_io_codefresh_pipeline_id) (\n  max by (pod, label_io_codefresh_pipeline_id) (\n    container_memory_usage_bytes{pod=~\"^dind-[0-9].*\", container_name!=\"POD\"}\n    * on(pod) group_left(label_io_codefresh_pipeline_id) \n    kube_pod_labels{label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Volume Consumption(MAX)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (io_codefresh_pipeline_id) (\n\t(docker_volume_kb_total{io_codefresh_pipelineId=\"$pipeline_id\"} - docker_volume_kb_available{io_codefresh_pipelineId=\"$pipeline_id\"})\n)"
    }
   ]
  },
  {
   "title": "CPU Percentage Usage (AVG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max ( \n  (\n    (max by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"^dind-[0-9].*\",container!=\"POD\"}[40s]))) /\n    (max by (pod) (kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\",pod=~\"^dind-[0-9].*\"}))\n  )\n  * on(pod) group_left(label_io_codefresh_pipeline_id) \n  kube_pod_labels{label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\"}\n)"
    }
   ]
  },
  {
   "title": "Memory Percentage Usage (AVG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max (\n  ( \n    ( max by (pod) (container_memory_usage_bytes{pod=~\"^dind-[0-9].*\", container_name!=\"POD\"}) ) / \n    ( max by (pod) (kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\",pod=~\"^dind-[0-9].*\"})  )\n  )\n  * on(pod) group_left(label_io_codefresh_pipeline_id) \n  kube_pod_labels{label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\"}\n)"
    }
   ]
  },
  {
   "title": "CPU Percentage Usage (MAX)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max ( \n  (\n    (max by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"^dind-[0-9].*\",container!=\"POD\"}[40s]))) /\n    (max by (pod) (kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\",pod=~\"^dind-[0-9].*\"}))\n  )\n  * on(pod) group_left(label_io_codefresh_pipeline_id) \n  kube_pod_labels{label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\"}\n)"
    }
   ]
  },
  {
   "title": "Memory Percentage Usage (AVG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max (\n  ( \n    ( max by (pod) (container_memory_usage_bytes{pod=~\"^dind-[0-9].*\", container_name!=\"POD\"}) ) / \n    ( max by (pod) (kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\",pod=~\"^dind-[0-9].*\"})  )\n  )\n  * on(pod) group_left(label_io_codefresh_pipeline_id) \n  kube_pod_labels{label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\"}\n)"
    }
   ]
  },
  {
   "title": "Pipeline CPU Consumption",
   "type": "timeseries",
   "description": "Consumption of CPU for the specified pipeline.\nBroken down per build ID and aggregated for the whole pipeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without (pod) (\n  avg by (pod) (\n    rate(container_cpu_usage_seconds_total{pod=~\"^dind-.*\",container!=\"POD\"}[40s])\n  )\n  * on(pod) group_left(label_io_codefresh_pipeline_id) \n  kube_pod_labels{label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\"}\n)",
     "legendFormat": "Pipeline(avg)={{label_io_codefresh_pipeline_id}}"
    },
    {
     "expr": "avg by (pod) (\n  rate(container_cpu_usage_seconds_total{pod=~\"^dind-.*\",container!=\"POD\"}[40s])\n)\n* on(pod) group_left(label_io_codefresh_pipeline_id) \nkube_pod_labels{label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\"}",
     "legendFormat": "Build={{pod}}"
    }
   ]
  },
  {
   "title": "Pipeline Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (label_io_codefresh_pipeline_id) (\n  avg by (pod, label_io_codefresh_pipeline_id) (\n    container_memory_usage_bytes{pod=~\"^dind-[0-9].*\", container_name!=\"POD\"}\n    * on(pod) group_left(label_io_codefresh_pipeline_id) \n    kube_pod_labels{label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\"}\n  )\n)",
     "legendFormat": "Pipeline(avg)={{label_io_codefresh_pipeline_id}}"
    },
    {
     "expr": "\n  avg by (pod, label_io_codefresh_pipeline_id) (\n    container_memory_usage_bytes{pod=~\"^dind-[0-9].*\", container_name!=\"POD\"}\n    * on(pod) group_left(label_io_codefresh_pipeline_id) \n    kube_pod_labels{label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\"}\n  )\n",
     "legendFormat": "Build={{pod}}"
    }
   ]
  },
  {
   "title": "Pipeline Volume Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "avg by (io_codefresh_pipeline_id) (\n\t(docker_volume_kb_total{io_codefresh_pipelineId=\"$pipeline_id\"} - docker_volume_kb_available{io_codefresh_pipelineId=\"$pipeline_id\"})\n)",
     "legendFormat": "Pipeline(avg)=$pipeline_id"
    },
    {
     "expr": "(docker_volume_kb_total{io_codefresh_pipelineId=\"$pipeline_id\"} - docker_volume_kb_available{io_codefresh_pipelineId=\"$pipeline_id\"})",
     "legendFormat": "Build={{dind_pod_name}}"
    }
   ]
  }
 ]
}