{
 "title": "Workflow init phase duration (avg)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "error_threshold", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "K8s Ops Average Duration (dinds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(kubernetes_events_duration{event_name=~\"dind-[0-9].*\", event_reason=\"FailedScheduling\", event_message!~\"pod has unbound immediate PersistentVolumeClaims.*\"} !=0< $error_threshold) by (event_reason)",
     "legendFormat": "(Pod Scheduling) (dind)"
    },
    {
     "expr": "avg(kubernetes_events_timestamp{event_name=~\"dind-[0-9].*\", event_reason=\"ProvisioningSucceeded\"} - on(event_name) kubernetes_events_timestamp{event_name=~\"dind-[0-9].*\", event_reason=\"ExternalProvisioning\"} + scalar(avg(kubernetes_events_duration{event_name=~\"dind-[0-9].*\", event_reason=\"FailedScheduling\", event_message=~\".*has unbound.*\"}))) by (event_reason)",
     "legendFormat": "(Volume Provisioning)  (dind)"
    },
    {
     "expr": "avg(kubernetes_events_timestamp{event_name=~\"dind-[0-9].*\", event_reason=\"Pulled\"} - on(event_name) label_replace(kubernetes_events_timestamp{event_reason=\"ProvisioningSucceeded\"}, \"event_name\", \"$2\", \"event_name\", \"(pvc-)(dind-[0-9].*)\")) by (event_reason)",
     "legendFormat": "(Volume Attach & Mount)  (dind)"
    },
    {
     "expr": "avg(kubernetes_events_timestamp{event_name=~\"dind-[0-9].*\", event_reason=\"Created\"} - on(event_name) kubernetes_events_timestamp{event_name=~\"dind-[0-9].*\", event_reason=\"Pulled\"}) by (event_reason)",
     "legendFormat": "(Pod Creation)  (dind)"
    },
    {
     "expr": "avg(kubernetes_events_duration{event_name=~\"dind-[0-9].*\", event_reason!~\"Killing|FailedScheduling|ExternalProvisioning|Provisioning|NotTriggerScaleUp\", event_type!=\"Warning\"} !=0< $error_threshold) by (event_reason)",
     "legendFormat": "{{event_reason}} (dind)"
    },
    {
     "expr": "avg(kubernetes_events_duration{event_name=~\"engine-[0-9].*\", event_reason=\"FailedScheduling\"} !=0< $error_threshold) by (event_reason)",
     "legendFormat": "(Pod Scheduling) (engine)"
    },
    {
     "expr": "avg(kubernetes_events_timestamp{event_name=~\"engine-[0-9].*\", event_reason=\"Created\"} - on(event_name) kubernetes_events_timestamp{event_name=~\"engine-[0-9].*\", event_reason=\"Scheduled\"}) by (event_reason)",
     "legendFormat": "(Pod Creation) (engine)"
    },
    {
     "expr": "avg(kubernetes_events_duration{event_name=~\"engine-[0-9].*\", event_reason!~\"Killing|FailedScheduling\", event_type!=\"Warning\"} !=0< $error_threshold) by (event_reason)",
     "legendFormat": "{{event_reason}}"
    }
   ]
  },
  {
   "title": "Init Steps Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(workflow_step_duration{phase_name=\"presteps\"} <$error_threshold) by (step_name)",
     "legendFormat": "{{step_name}}"
    }
   ]
  },
  {
   "title": "Steps & K8s Ops Averages Diagram",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(workflow_step_duration{phase_name=\"presteps\"} !=0<$error_threshold and on(kubernetes_pod_name) changes(workflow_phase_status{}[40s]) == 1) by (step_name)",
     "legendFormat": "{{step_name}}"
    },
    {
     "expr": "avg(kubernetes_events_timestamp{event_name=~\"dind-[0-9].*\", event_reason=\"ProvisioningSucceeded\"} - on(event_name) kubernetes_events_timestamp{event_name=~\"dind-[0-9].*\", event_reason=\"ExternalProvisioning\"} + scalar(avg(kubernetes_events_duration{event_name=~\"dind-[0-9].*\", event_reason=\"FailedScheduling\", event_message=~\".*has unbound.*\"}))) by (event_reason)",
     "legendFormat": "K8: {{Volume Provisioning}}  (dind)"
    },
    {
     "expr": "avg(kubernetes_events_duration{event_name=~\"dind-[0-9].*\", event_reason=\"FailedScheduling\", event_message!~\"pod has unbound immediate PersistentVolumeClaims.*\"} !=0< $error_threshold) by (event_reason)",
     "legendFormat": "K8: {{Pod Scheduling}} (dind)"
    },
    {
     "expr": "avg(kubernetes_events_timestamp{event_name=~\"dind-[0-9].*\", event_reason=\"Pulled\"} - on(event_name) label_replace(kubernetes_events_timestamp{event_reason=\"ProvisioningSucceeded\"}, \"event_name\", \"$2\", \"event_name\", \"(pvc-)(dind-[0-9].*)\")) by (event_reason)",
     "legendFormat": "K8: {{Volume Attach & Mount}}  (dind)"
    },
    {
     "expr": "avg(kubernetes_events_timestamp{event_name=~\"dind-[0-9].*\", event_reason=\"Created\"} - on(event_name) kubernetes_events_timestamp{event_name=~\"dind-[0-9].*\", event_reason=\"Pulled\"}) by (event_reason)",
     "legendFormat": "K8: {{Pod Creation}}  (dind)"
    },
    {
     "expr": "avg(kubernetes_events_duration{event_type!=\"Warning\", event_name=~\"dind-[0-9].*\", event_reason!~\"Killing|FailedScheduling|ExternalProvisioning|Provisioning|FailedAttachVolume|NotTriggerScaleUp\"} !=0<$error_threshold) by (event_reason)",
     "legendFormat": "K8: {{event_reason}} (dind)"
    },
    {
     "expr": "avg(kubernetes_events_duration{event_type!=\"Warning\", event_name=~\"engine-[0-9].*\", event_reason!~\"Killing|FailedScheduling\"} !=0<$error_threshold) by (event_reason)",
     "legendFormat": "K8: {{event_reason}} (engine)"
    },
    {
     "expr": "avg(kubernetes_events_duration{event_name=~\"engine-[0-9].*\", event_reason=\"FailedScheduling\"} !=0< $error_threshold) by (event_reason)",
     "legendFormat": "K8:  {{Pod Scheduling}} (engine)"
    },
    {
     "expr": "avg(kubernetes_events_timestamp{event_name=~\"engine-[0-9].*\", event_reason=\"Created\"} - on(event_name) kubernetes_events_timestamp{event_name=~\"engine-[0-9].*\", event_reason=\"Scheduled\"}) by (event_reason)",
     "legendFormat": "K8:  {{Pod Creation}} (engine)"
    }
   ]
  },
  {
   "title": "K8s Events Warnings Count",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kubernetes_events_duration{event_type=\"Warning\", event_message!~\"pod has unbound immediate PersistentVolumeClaims.*\"}) by (event_reason)",
     "legendFormat": "{{event_reason}} "
    }
   ]
  },
  {
   "title": "Abnormal Durations",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kubernetes_events_duration{event_reason!~\"Killing\", event_name=~\"engine-[0-9].*|dind-[0-9].*\", event_message!~\"pod has unbound immediate PersistentVolumeClaims.*|.* has \\\"karpenter.sh/do-not-disrupt\\\" annotation\"} !=0>$error_threshold",
     "legendFormat": "{{event_reason}} ({{event_name}}) {{event_message}}"
    },
    {
     "expr": "workflow_step_duration{phase_name=\"presteps\"} !=0>$error_threshold",
     "legendFormat": "{{step_name}} ({{kubernetes_pod_name}})"
    }
   ]
  }
 ]
}